## **Task 0: Warm-up exercise**

In [2]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    """ Perform vector addition
    """
    if len(vec1) != len(vec2):
        raise ValueError('Two vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec1[i] = vec1[i] + vec2[i]
    
    return vec1
    

In [3]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
inplace_add_vectors(v1, v2)
print(v1)

[5, 7, 9]


In [4]:
def add_vectors(vec1: list, vec2: list) -> list:
    """ Return a new vector where each element is 
    the sum of the corresponding elements from vec1 and vec2.
    """
    vec3 = []
    if len(vec1) != len(vec2):
        raise ValueError('Two given vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec3.append(vec1[i] + vec2[i])
    return vec3

In [5]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
v3 = add_vectors(v1, v2)
print(v1)
print(v3) 

[1, 2, 3]
[5, 7, 9]


## **Task 1: Matrix Operations**

In [6]:
import numpy as np

# Create a large matrix:
n, m = 5000, 5000
min, max = 0, 100
matrix = np.random.randint(min, max, size = (n, m))

print(matrix)


[[41 25  0 ... 61 97 23]
 [86  5 16 ... 31  3 65]
 [89 74 23 ...  0 83 70]
 ...
 [84 25 27 ... 54 35 76]
 [78 18 35 ... 77 27 30]
 [53 43 65 ... 28  2 34]]


In [7]:
np.shape(matrix)

(5000, 5000)

In [8]:
# Mean function
def compute_mean(matrix):
    """Calculate the average of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
    
    return sum / num_entry
    

In [9]:
compute_mean(matrix)

np.float64(49.49677892)

In [10]:
# Variance function:
def compute_variance(matrix):
    """Calculate the variance of the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum_square_diff = 0
    mean = compute_mean(matrix)
    for i in range(rows):
        for j in range(cols):
            sum_square_diff += (mean - matrix[i][j]) ** 2
            
    variance = sum_square_diff / num_entry
    return variance

In [11]:
compute_variance(matrix)

np.float64(833.3119783391523)

In [12]:
def compute_sum(matrix):
    """  Returns the total sum of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0 
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
            
    return sum

In [13]:
compute_sum(matrix)

np.int64(1237419473)

In [14]:
def compute_mupltiply(matrix, number):
    """ returns a new matrix 
    where each number in the input matrix is multiplied by a given number.
    """
    new_matrix = matrix.copy()
    
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            new_matrix[i][j] = number * matrix[i][j]
            
    return new_matrix

In [15]:
compute_mupltiply(matrix, 2)

array([[ 82,  50,   0, ..., 122, 194,  46],
       [172,  10,  32, ...,  62,   6, 130],
       [178, 148,  46, ...,   0, 166, 140],
       ...,
       [168,  50,  54, ..., 108,  70, 152],
       [156,  36,  70, ..., 154,  54,  60],
       [106,  86, 130, ...,  56,   4,  68]])

## **Task 2: Stencil matrix**

In [52]:
# Create a stencil matrix
n = 50
A = np.zeros((n,n))

for i in range(n):
    A[i, i] = -2
    A[i, i - 1] = 1
    if i < n -1:
        A[i, i + 1] = 1
    
print(A)

[[-2.  1.  0. ...  0.  0.  1.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]


In [42]:
# Create a random vector with 50 entries:
v = np.random.rand(n)

N = 100  # Number of interations
for _ in range(N):
    v = np.dot(A, v)
    v = v / np.linalg.norm(v)

# Approximated dominant eigenvalue
app_dominant = np.dot(v, np.dot(A, v)) / np.dot(v,v)

# Actual eigenvalues
Lambda, V = np.linalg.eig(A)
exact_dominant = np.max(np.abs(Lambda))

print('-' * 75)
print('|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)


---------------------------------------------------------------------------
|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9903601344             |           3.9963511084         |
---------------------------------------------------------------------------


## **Task 3: Challenge exercise**

In [49]:
def multiply_efficient(v: list) -> None:
    """
    Computes the matrix-vector product without requiring the matrix.

    Args:
        v (list): a vector of size n.
    
    Returns:
        w (np.ndarray): the resultant vector after matrix-vector multiplication.
    
    """

    n = len(v)
    w = np.zeros(n)
    
    w[0] = -2 * v[0] + v[1]
    
    for i in range(1, n-1):
        w[i] = v[i-1] - 2 * v[i] + v[i + 1]
        
    w[n-1] = v[n-2] - 2 * v[n-1]
    
    return w

In [51]:
for _ in range(N):
    v = multiply_efficient(v)
    v = v / np.linalg.norm(v)
    
app_dominant_1 = np.dot(v, multiply_efficient(v)) / np.dot(v,v)

print('-' * 75)
print('|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant_1:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)

---------------------------------------------------------------------------
|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9927005614             |           3.9963511084         |
---------------------------------------------------------------------------
