## **Task 0: Warm-up exercise**

First we create the inplace add vector function:

In [34]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    """ Perform vector addition
    """
    if len(vec1) != len(vec2):
        raise ValueError('Two vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec1[i] = vec1[i] + vec2[i]
    
    return vec1

v1 = [1, 2, 3]
v2 = [4, 5, 6]
inplace_add_vectors(v1, v2)
print(v1)

[5, 7, 9]


Then we create the add vector function

In [35]:
def add_vectors(vec1: list, vec2: list) -> list:
    """ Return a new vector where each element is 
    the sum of the corresponding elements from vec1 and vec2.
    """
    vec3 = []
    if len(vec1) != len(vec2):
        raise ValueError('Two given vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec3.append(vec1[i] + vec2[i])
    return vec3

v1 = [1, 2, 3]
v2 = [4, 5, 6]
v3 = add_vectors(v1, v2)

print(v3) 

[5, 7, 9]


## **Task 1: Matrix Operations**

In [36]:
import numpy as np

# Create a large matrix:
n, m = 5000, 5000
min, max = 0, 100
matrix = np.random.randint(min, max, size = (n, m))

print(matrix)


[[96 18 95 ... 21  9 46]
 [10 69 37 ...  4 15 15]
 [23 56  3 ... 14 85 46]
 ...
 [61 34 22 ... 81 88 23]
 [14 55 91 ...  9 66 36]
 [44 87 27 ...  9 40  7]]


In [37]:
np.shape(matrix)

(5000, 5000)

In [38]:
# Mean function
def compute_mean(matrix):
    """Calculate the average of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
    
    return sum / num_entry
    

In [39]:
compute_mean(matrix)

49.50048368

In [40]:
# Variance function:
def compute_variance(matrix):
    """Calculate the variance of the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum_square_diff = 0
    mean = compute_mean(matrix)
    for i in range(rows):
        for j in range(cols):
            sum_square_diff += (mean - matrix[i][j]) ** 2
            
    variance = sum_square_diff / num_entry
    return variance

In [41]:
compute_variance(matrix)

833.0699129639456

In [42]:
def compute_sum(matrix):
    """  Returns the total sum of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0 
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
            
    return sum

In [43]:
compute_sum(matrix)

1237512092

In [44]:
def compute_mupltiply(matrix, number):
    """ returns a new matrix 
    where each number in the input matrix is multiplied by a given number.
    """
    new_matrix = matrix.copy()
    
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            new_matrix[i][j] = number * matrix[i][j]
            
    return new_matrix

In [45]:
compute_mupltiply(matrix, 2)

array([[192,  36, 190, ...,  42,  18,  92],
       [ 20, 138,  74, ...,   8,  30,  30],
       [ 46, 112,   6, ...,  28, 170,  92],
       ...,
       [122,  68,  44, ..., 162, 176,  46],
       [ 28, 110, 182, ...,  18, 132,  72],
       [ 88, 174,  54, ...,  18,  80,  14]])

## **Task 2: Stencil matrix**

In [46]:
# Create a stencil matrix
def create_stencil_matrix(n):
    A = np.zeros((n, n))
    
    for i in range(n):
        A[i, i] = -2  # Diagonal elements
        
        if i > 0:
            A[i, i-1] = 1  # Lower 1
        
        if i < n-1:
            A[i, i+1] = 1  # Upper 1
            
    return A
    
print(create_stencil_matrix(50))

[[-2.  1.  0. ...  0.  0.  0.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]


In [47]:
# Create a random vector with 50 entries:
v = np.random.rand(n)

N = 100  # Number of interations
for _ in range(N):
    v = np.dot(A, v)
    v = v / np.linalg.norm(v)

# Approximated dominant eigenvalue
app_dominant = np.dot(v, np.dot(A, v)) / np.dot(v,v)

# Actual eigenvalues
Lambda, V = np.linalg.eig(A)
exact_dominant = np.max(np.abs(Lambda))

print('-' * 75)
print('|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)


ValueError: shapes (50,50) and (5000,) not aligned: 50 (dim 1) != 5000 (dim 0)

## **Task 3: Challenge exercise**

In [ ]:
def multiply_efficient(v: list) -> None:
    """
    Computes the matrix-vector product without requiring the matrix.

    Args:
        v (list): a vector of size n.
    
    Returns:
        w (np.ndarray): the resultant vector after matrix-vector multiplication.
    
    """

    n = len(v)
    w = np.zeros(n)
    
    w[0] = -2 * v[0] + v[1]
    
    for i in range(1, n-1):
        w[i] = v[i-1] - 2 * v[i] + v[i + 1]
        
    w[n-1] = v[n-2] - 2 * v[n-1]
    
    return w

In [ ]:
for _ in range(N):
    v = multiply_efficient(v)
    v = v / np.linalg.norm(v)
    
app_dominant_1 = np.dot(v, multiply_efficient(v)) / np.dot(v,v)

print('-' * 75)
print('|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant_1:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)

---------------------------------------------------------------------------
|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9939755033             |           3.9963511084         |
---------------------------------------------------------------------------
