## **Task 0: Warm-up exercise**

First we create the inplace add vector function_

In [1]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    """ Perform vector addition
    """
    if len(vec1) != len(vec2):
        raise ValueError('Two vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec1[i] = vec1[i] + vec2[i]
    
    return vec1

v1 = [1, 2, 3]
v2 = [4, 5, 6]
inplace_add_vectors(v1, v2)
print(v1)

[5, 7, 9]


Then we create the add vector function

In [2]:
def add_vectors(vec1: list, vec2: list) -> list:
    """ Return a new vector where each element is 
    the sum of the corresponding elements from vec1 and vec2.
    """
    vec3 = []
    if len(vec1) != len(vec2):
        raise ValueError('Two given vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec3.append(vec1[i] + vec2[i])
    return vec3

In [3]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
v3 = add_vectors(v1, v2)

print(v3) 

[5, 7, 9]


## **Task 1: Matrix Operations**

In [4]:
import numpy as np

# Create a large matrix:
n, m = 5000, 5000
min, max = 0, 100
matrix = np.random.randint(min, max, size = (n, m))

print(matrix)


[[41 93 94 ... 20 94  4]
 [57 31 56 ... 57 34 57]
 [91 54 43 ... 14 99 89]
 ...
 [96 32 68 ... 41 54 66]
 [40 55 90 ... 19 75  2]
 [39 11 30 ... 51 51 80]]


In [5]:
np.shape(matrix)

(5000, 5000)

In [6]:
# Mean function
def compute_mean(matrix):
    """Calculate the average of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
    
    return sum / num_entry
    

In [7]:
compute_mean(matrix)

49.50252896

In [8]:
# Variance function:
def compute_variance(matrix):
    """Calculate the variance of the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum_square_diff = 0
    mean = compute_mean(matrix)
    for i in range(rows):
        for j in range(cols):
            sum_square_diff += (mean - matrix[i][j]) ** 2
            
    variance = sum_square_diff / num_entry
    return variance

In [9]:
compute_variance(matrix)

833.283564479314

In [10]:
def compute_sum(matrix):
    """  Returns the total sum of all numbers in the matrix
    """
    rows, cols  = matrix.shape
    num_entry = matrix.size
    
    sum = 0 
    for i in range(rows):
        for j in range(cols):
            sum += matrix[i][j]
            
    return sum

In [11]:
compute_sum(matrix)

1237563224

In [12]:
def compute_mupltiply(matrix, number):
    """ returns a new matrix 
    where each number in the input matrix is multiplied by a given number.
    """
    new_matrix = matrix.copy()
    
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            new_matrix[i][j] = number * matrix[i][j]
            
    return new_matrix

In [13]:
compute_mupltiply(matrix, 2)

array([[ 82, 186, 188, ...,  40, 188,   8],
       [114,  62, 112, ..., 114,  68, 114],
       [182, 108,  86, ...,  28, 198, 178],
       ...,
       [192,  64, 136, ...,  82, 108, 132],
       [ 80, 110, 180, ...,  38, 150,   4],
       [ 78,  22,  60, ..., 102, 102, 160]])

## **Task 2: Stencil matrix**

In [14]:
# Create a stencil matrix
n = 50
A = np.zeros((n,n))

for i in range(n):
    A[i, i] = -2
    A[i, i - 1] = 1
    if i < n -1:
        A[i, i + 1] = 1
    
print(A)

[[-2.  1.  0. ...  0.  0.  1.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]


In [15]:
# Create a random vector with 50 entries:
v = np.random.rand(n)

N = 100  # Number of interations
for _ in range(N):
    v = np.dot(A, v)
    v = v / np.linalg.norm(v)

# Approximated dominant eigenvalue
app_dominant = np.dot(v, np.dot(A, v)) / np.dot(v,v)

# Actual eigenvalues
Lambda, V = np.linalg.eig(A)
exact_dominant = np.max(np.abs(Lambda))

print('-' * 75)
print('|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)


---------------------------------------------------------------------------
|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9863713462             |           3.9963511084         |
---------------------------------------------------------------------------


## **Task 3: Challenge exercise**

In [16]:
def multiply_efficient(v: list) -> None:
    """
    Computes the matrix-vector product without requiring the matrix.

    Args:
        v (list): a vector of size n.
    
    Returns:
        w (np.ndarray): the resultant vector after matrix-vector multiplication.
    
    """

    n = len(v)
    w = np.zeros(n)
    
    w[0] = -2 * v[0] + v[1]
    
    for i in range(1, n-1):
        w[i] = v[i-1] - 2 * v[i] + v[i + 1]
        
    w[n-1] = v[n-2] - 2 * v[n-1]
    
    return w

In [17]:
for _ in range(N):
    v = multiply_efficient(v)
    v = v / np.linalg.norm(v)
    
app_dominant_1 = np.dot(v, multiply_efficient(v)) / np.dot(v,v)

print('-' * 75)
print('|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant_1:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)

---------------------------------------------------------------------------
|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9955283706             |           3.9963511084         |
---------------------------------------------------------------------------
