# Exercise 5

Navn på gruppemedlemmer: Le Uyen Nhu Dinh og Henrik Hellem

Epost gruppemedlemmer: "le.uyen.nhu.dinh@nmbu.no","henrik.hellem@nmbu.no"

## **Task 0: Warm-up exercise**

First we create the inplace add vector function:

In [122]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    """ Perform vector addition
    """
    if len(vec1) != len(vec2):
        raise ValueError('Two vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec1[i] = vec1[i] + vec2[i]
    
    return vec1

v1 = [1, 2, 3]
v2 = [4, 5, 6]
inplace_add_vectors(v1, v2)
print(v1)

[5, 7, 9]


Then we create the add vector function

In [123]:
def add_vectors(vec1: list, vec2: list) -> list:
    """ Return a new vector where each element is 
    the sum of the corresponding elements from vec1 and vec2.
    """
    vec3 = []
    if len(vec1) != len(vec2):
        raise ValueError('Two given vectors do not have the same dimension')
    
    for i in range(len(vec1)):
        vec3.append(vec1[i] + vec2[i])
    return vec3

v1 = [1, 2, 3]
v2 = [4, 5, 6]
v3 = add_vectors(v1, v2)

print(v3) 

[5, 7, 9]


## **Task 1: Matrix Operations**

First we create the matrix as a numpy array:

In [124]:
import numpy as np

# Create a large matrix:
array = np.random.randint(0, 101, size=(5000, 5000))
print(array)

[[ 6 50 63 ... 46 87 25]
 [94 60 87 ... 22 86  1]
 [22 86 49 ... 96  3 69]
 ...
 [ 5  2 14 ... 10 16 44]
 [36 47 14 ... 73 86 46]
 [40 85 97 ... 57 40 65]]


We write a function to find the total sum of entries in the matrix

In [125]:
def total_sum_matrix(matrix: list) -> int:
    return sum(sum(row) for row in matrix)

print(f"Total sum: {total_sum_matrix(array)}")

Total sum: 1249855617


Then we find the mean value:

In [126]:
# Mean function
def mean_matrix(matrix: list) -> float:
    total_entries = len(matrix) * len(matrix[0])
    return total_sum_matrix(matrix) / total_entries

print(f"Mean: {mean_matrix(array)}")
    

Mean: 49.99422468


Furthermore we find the variance

In [127]:
# Function to find variance
def variance_matrix(matrix: list) -> float:
    mean = mean_matrix(matrix)
    total_entries = len(matrix) * len(matrix[0])
    
    # Find the sum of ((\mu - A_{ij} )
    total_squared_diff = sum((element - mean) ** 2 for row in matrix for element in row)
    
    # Calculate variance
    variance = total_squared_diff / total_entries
    
    return variance

print(f"Variance: {variance_matrix(array)}")

Variance: 849.8951869296943


Lastly we write a function to multiply the matrix with a given number

In [128]:
# Function to multiply matrix by given number
def multiply_matrix_by_number(matrix: list, number: int) -> list:
    # Create a deep copy of the matrix to avoid modifying the original matrix
    multiplied_matrix = matrix.copy()
    
    for row in range(len(multiplied_matrix)):
        for col in range(len(multiplied_matrix[0])):
            multiplied_matrix[row][col] *= number
    
    return multiplied_matrix
    

# Choose 4 as given number:
print(f"Multiply by given n, where n=4: {multiply_matrix_by_number(array, 4)}")

Multiply by given n, where n=4: [[ 24 200 252 ... 184 348 100]
 [376 240 348 ...  88 344   4]
 [ 88 344 196 ... 384  12 276]
 ...
 [ 20   8  56 ...  40  64 176]
 [144 188  56 ... 292 344 184]
 [160 340 388 ... 228 160 260]]


## **Task 2: Stencil matrix**

In [129]:
# Create a stencil matrix
def create_stencil_matrix(n):
    A = np.zeros((n, n))
    
    for i in range(n):
        A[i, i] = -2  # Diagonal elements
        
        if i > 0:
            A[i, i-1] = 1  # Lower 1
        
        if i < n-1:
            A[i, i+1] = 1  # Upper 1
            
    return A
    
A = create_stencil_matrix(50)
print(A)

[[-2.  1.  0. ...  0.  0.  0.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]


In [130]:
# Create a random vector with 50 entries:
v = np.random.rand(50)

N = 100  # Number of interations
for _ in range(N):
    v = np.dot(A, v)
    v = v / np.linalg.norm(v)

# Approximated dominant eigenvalue
app_dominant = np.dot(v, np.dot(A, v)) / np.dot(v,v)

# Actual eigenvalues
Lambda, V = np.linalg.eig(A)
exact_dominant = np.max(np.abs(Lambda))

print('-' * 75)
print('|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)


---------------------------------------------------------------------------
|    Approximated Dominant Eigenvalue    |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9922414813             |           3.9962066575         |
---------------------------------------------------------------------------


## **Task 3: Challenge exercise**

In [131]:
def multiply_efficient(v: list) -> None:
    """
    Computes the matrix-vector product without requiring the matrix.

    Args:
        v (list): a vector of size n.
    
    Returns:
        w (np.ndarray): the resultant vector after matrix-vector multiplication.
    
    """

    n = len(v)
    w = np.zeros(n)
    
    w[0] = -2 * v[0] + v[1]
    
    for i in range(1, n-1):
        w[i] = v[i-1] - 2 * v[i] + v[i + 1]
        
    w[n-1] = v[n-2] - 2 * v[n-1]
    
    return w

In [132]:
for _ in range(N):
    v = multiply_efficient(v)
    v = v / np.linalg.norm(v)
    
app_dominant_1 = np.dot(v, multiply_efficient(v)) / np.dot(v,v)

print('-' * 75)
print('|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |')
print('-' * 75)
print(f'|              {app_dominant_1:.10f}             |           {exact_dominant:.10f}         |')
print('-' * 75)

---------------------------------------------------------------------------
|  Approximated Dominant Eigenvalue (*)  |    Actual Dominant Eigenvalue  |
---------------------------------------------------------------------------
|              -3.9941670081             |           3.9962066575         |
---------------------------------------------------------------------------
